spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 0408Heart1611
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    publisher-confirm-type: correlated
    publisher-returns: true
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: 0408Heart1611
  cache:
    cache-names: menus_cache
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 8081
  compression:
    enabled: true
mybatis:
  configuration:
      lazy-loading-enabled: true
      cache-enabled: false
fastdfs:
  nginx:
    host: http://127.0.0.1/

